name: CI

on: [push, pull_request]

jobs:
  html_documentation_checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install python packages
        run: |
          pip install --user pytidylib
          pip install --user futures
      - name: Build html tidy
        run: |
          git clone --branch 5.8.0 --depth=1 https://github.com/htacg/tidy-html5.git
          pushd tidy-html5
          cmake .
          make
          sudo make install
          popd
          sudo ldconfig
      - name: Tidy html
        run: python ./.CI/check_html.py tidyHTML ./A_Modelica/DroneLibrary
      - name: Check tags
        run: python ./.CI/check_html.py checkTags ./A_Modelica/DroneLibrary
  syntax_checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Check file encoding
        run: "! find . -name '*.mo' -exec bash -c 'iconv -o /dev/null -f utf8 -t utf8 \"{}\" |& sed \"s,^,{}: ,\"' ';' | grep '.'"
      - name: Check for UTF-8 BOM
        run: "! find . -name '*.mo' -print0 | xargs -0 grep -l $'^\\xEF\\xBB\\xBF' | grep ."
      - name: Get moparser
        run: git clone --depth=1 https://github.com/modelica-tools/ModelicaSyntaxChecker
      - name: Check syntax
        run: ModelicaSyntaxChecker/Linux64/moparser -v 3.4 -r A_Modelica/DroneLibrary
#  deprecation_checks:
#    timeout-minutes: 5
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 5
#      - name: Setup python environment
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8
#      - name: Check deprecated Text.lineColor annotation
#        run: python ./.CI/check_deprecated_line_color.py A_Modelica/DroneLibrary
